export const surpriseMePrompts = [
  "A cat wearing sunglasses with a caption: 'Too cool for school.'",
  "A dog sitting at a computer with a thought bubble saying: 'Can't believe I ate the homework.'",
  "Two penguins having a conversation with a speech bubble that says: 'What do you mean, we're out of fish?'",
  "A squirrel holding a tiny umbrella with the text: 'Preparing for a rainy day.'",
  "A bear sitting on a couch surrounded by empty pizza boxes and chips bags with the caption: 'Netflix and bear.'",
  "A group of ducks crossing the road with a sign that says: 'Duck crossing, quack quack.'",
  "A koala hugging a tree with the words: 'Tree hugger for life.'",
  "A monkey wearing a crown with the text: 'King of the jungle gym.'",
  "A llama wearing sunglasses with a speech bubble saying: 'Llamazing!'",
  "A horse wearing a party hat with the caption: 'Neighs and celebrations.'",
  "A giraffe peeking over a fence with the words: 'Just checking out the view.'",
  "A sheep with a cup of coffee and a book with the text: 'Sheepishly enjoying my day.'",
  "A hedgehog holding a tiny broom with the words: 'Time to clean up my act.'",
  "A frog wearing a chef's hat with the caption: 'Hoppy cooking!'",
  "A crab with a beach umbrella and a drink with the text: 'Crabby but happy.'",
  "A snail with a jetpack with a speech bubble saying: 'Zooming into the weekend.'",
  "A panda doing yoga with the words: 'Finding my inner peace.'",
  "A fish wearing a snorkel with the caption: 'Just keep swimming.'",
  "A rabbit with a magician's hat and wand with the text: 'Now you see me, now you don't.'",
  "A turtle wearing running shoes with a speech bubble saying: 'Slow and steady wins the race.'",
  "A kangaroo with a basketball and a hoop with the words: 'Dunkaroo!'",
  "A fox wearing a detective hat with a magnifying glass and the caption: 'Solving mysteries, one clue at a time.'",
  "A butterfly with a camera and a map with the text: 'Exploring the world, one flutter at a time.'",
  "A lion with a microphone and sunglasses with the words: 'Roar like nobody's listening.'",
  "An owl wearing glasses with a book and the caption: 'Night owl reading.'",
  "A bee with a briefcase and a tie with the text: 'Buzziness as usual.'",
  "A deer with a chef's hat cooking in the kitchen with the words: 'Oh deer, it's dinner time.'",
  "A parrot wearing headphones with a microphone and the caption: 'Polly wants a DJ.'",
  "A walrus playing the saxophone with a speech bubble saying: 'Walu-sax.'",
  "A raccoon with a treasure map and a shovel with the text: 'Raccoon's hidden stash.'",
  "A seagull with a surfboard and sunglasses with the caption: 'Catchin' waves.'",
  "A gorilla with a crown and a scepter with the words: 'King of the jungle.'",
  "A platypus with a detective hat and a magnifying glass with the text: 'Platypus P.I.'",
  "A squirrel with a backpack and a compass with the caption: 'Nuts about adventure.'",
  "A camel with a backpack and a map with the words: 'Hump day hike.'",
  "A toucan with a paintbrush and an easel with the text: 'Toucan paint.'",
  "A flamingo with a camera and a tripod with the caption: 'Flamingle with photography.'",
  "A rhinoceros with a telescope and a star map with the words: 'Rhino stargazing.'",
  "A dragonfly with a jetpack and goggles with the text: 'Fly like a dragon.'",
  "A hummingbird with a paintbrush and a canvas with the caption: 'Tiny strokes of genius.'",
  "A crocodile with a snorkel and flippers with a speech bubble saying: 'Snappy swimmer.'",
  "A sloth with a telescope and a star map with the words: 'Sloth astronomy.'",
  "A hippopotamus with a snorkel and a pool float with the text: 'Hippo pool party.'",
  "A lobster with a chef's hat and a pot with the caption: 'Claws for celebration.'",
  "A skunk with a paintbrush and an easel with the words: 'Stinkin' art.'",
  "A blue jay with a camera and a tripod with the text: 'Capturing bird's-eye views.'",
  "A chameleon with sunglasses and a surfboard with the caption: 'Blendin' in with the waves.'",
  "A zebra with a microphone and a spotlight with the words: 'Stripes got talent.'"
];